version: '3'
services:
    # docker-compose up --no-deps blog
    # docker-compose up --no-recreate -d blog
    # docker-compose up --force-recreate -d blog
    # docker-compose up --no-deps -d blog
    # 需要设置 ossutil 需要的环境变量
    blog:
        container_name: blog
        image: wxnacy/hexo:latest
        ports:
            - 4000:4000
        volumes:
            - ./:/root/blog
        environment:
            - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
            - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
            - OSS_ENDPOINT=${OSS_ENDPOINT}
        restart: always
